version: "2.1"
services:
  #ToDo: Start a postgres container with name pgsql if no exists
  web:
    container_name: rlatech
    hostname: fis-wasser_rlatech_container
    image:
      pkorduan/r-latech:1.1.0
    links:
      - "pgsql:pgsql"
    volumes:
      - "/home/lung/lagebericht/scripts:/usr/local/lagebericht/scripts:ro"
      - "/home/lung/lagebericht/cache:/usr/local/lagebericht/cache:rw"
      - "/home/lung/lagebericht/logs:/usr/local/lagebericht/logs:rw"
      - "/home/lung/lagebericht/pdfs:/usr/local/lagebericht/pdfs:rw"
      - "/home/gisadmin/www/html:/usr/local/lagebericht/www:rw"
    environment:
      - TERM=linux
      - COLUMNS=80
      - LINES=120
